### ISSUE TITLE
helllo 

### ISSUE THREAD

**Issue by doterlm** [venshine/WheelView#12]
首先感谢你的分享  然后我想知道有没有方法改变wheelview的高度

**Comment by UFreedom** [comment]
@doterlm

wheelview 的高度是根据每个item的高度和总共滚轮数目决定的

wheelview_height = wheel_item_height \* wheel_item_size

一般情况下滚轮数目是固定的，所以你需要改变的是 wheel_item_height。所以重新写一个wheel item 的布局就好了

**Comment by doterlm** [comment]
嗯谢谢  找到了
