### ISSUE TITLE
wheel datas cannot be smaller than wheel size

### ISSUE THREAD

**Issue by kingwz** [venshine/WheelView#3]
1.list.size() < mWheelSize  
带副滚轮的时候 数据源必须大于滚轮的个数这个判断不合理了 
2.如何设置多级联动

**Comment by venshine** [comment]
感谢提供建议！
1.已取消数据源大于滚轮个数的判断；
2.多级联动设置只需两步：`mainWheelView.join(subWheelView);
        mainWheelView.joinDatas(createSubDatas());`，可以参考sample例子中的`initWheel1()`。
欢迎贡献代码，一起完善此框架。
