### ISSUE TITLE
gradle app 中引入后报错

### ISSUE THREAD

**Issue by hanq** [venshine/WheelView#31]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:28:9-36
  	is also present at [com.wx.wheelview:wheelview:1.3.3] AndroidManifest.xml:12:9-35 value=(true).
  	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:26:5-77:19 to override.

**Comment by venshine** [comment]
使用`tools:replace="android:allowBackup`暂时解决此问题吧，我稍候改一下allowBackup=false。
