### ISSUE TITLE
三级联动Bug

### ISSUE THREAD

**Issue by rewufu** [venshine/WheelView#4]
三级联动时，方法int getSelection()   T getSelectionItem()等方法失效，返回0或null

**Comment by venshine** [comment]
`int getSelection()`方法只有在`void setSelection()`设置后才有值，如果想要获取当前选中项索引可以使用`getCurrentPosition()`方法。我在三级联动时打印`T getSelectionItem()`方法都很正常，可以把你的log或者使用代码发出来看看。

**Comment by rewufu** [comment]
`private void initWheel1() {
        mainWheelView = (WheelView) findViewById(R.id.hour_wheelview);
        mainWheelView.setWheelAdapter(new ArrayWheelAdapter(this));
        mainWheelView.setSkin(WheelView.Skin.Holo);
        mainWheelView.setWheelData(createMainDatas());
        WheelView.WheelViewStyle style = new WheelView.WheelViewStyle();
        style.selectedTextSize = 20;
        style.textSize = 16;
        mainWheelView.setStyle(style);

```
    subWheelView = (WheelView) findViewById(R.id.minute_wheelview);
    subWheelView.setWheelAdapter(new ArrayWheelAdapter(this));
    subWheelView.setSkin(WheelView.Skin.Holo);
    subWheelView.setWheelData(createSubDatas().get(createMainDatas().get(mainWheelView.getSelection())));
    subWheelView.setStyle(style);
    mainWheelView.join(subWheelView);
    mainWheelView.joinDatas(createSubDatas());

    childWheelView = (WheelView) findViewById(R.id.second_wheelview);
    childWheelView.setWheelAdapter(new ArrayWheelAdapter(this));
    childWheelView.setSkin(WheelView.Skin.Holo);
    childWheelView.setWheelData(createChildDatas().get(createSubDatas().get(createMainDatas().get(mainWheelView
            .getSelection())).get(subWheelView.getSelection())));
    childWheelView.setStyle(style);
    subWheelView.join(childWheelView);
    subWheelView.joinDatas(createChildDatas());
}

private List<String> createMainDatas() {
    String[] strings = {"adv", "福安", "香格里拉", "鹿寨", "祥云",
            "大竹", "大理", "重庆", "张家港", "鹤庆",
            "沙县", "四川省", "平潭"};
    return Arrays.asList(strings);
}

private HashMap<String, List<String>> createSubDatas() {
    HashMap<String, List<String>> map = new HashMap<String, List<String>>();
    String[] strings = {"adv", "福安", "香格里拉", "鹿寨", "祥云",
            "大竹", "大理", "重庆", "张家港", "鹤庆",
            "沙县", "四川省", "平潭"};
    String[] s1 = {"不限"};
    String[] s2 = {"不限"};
    String[] s3 = {"不限"};
    String[] s4 = {"不限"};
    String[] s5 = {"不限"};
    String[] s6 = {"不限"};
    String[] s7 = {"不限"};
    String[] s8 = {"不限", "南岸", "九龙坡", "丰都", "渝中", "江北"};
    String[] s9 = {"不限"};
    String[] s10 = {"不限"};
    String[] s11 = {"不限"};
    String[] s12 = {"不限"};
    String[] s13 = {"不限"};
    String[][] ss = {s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13};
    for (int i = 0; i < strings.length; i++) {
        map.put(strings[i], Arrays.asList(ss[i]));
    }
    return map;
}

private HashMap<String, List<String>> createChildDatas() {
    HashMap<String, List<String>> map = new HashMap<String, List<String>>();
    String[] strings = {"不限", "不限", "不限", "不限", "不限", "不限", "不限", "不限", "南岸",
            "九龙坡", "丰都", "渝中", "江北", "不限", "不限", "不限", "不限", "不限"};
    String[] s1 = {"不限"};
    String[] s2 = {"不限"};
    String[] s3 = {"不限"};
    String[] s4 = {"不限"};
    String[] s5 = {"不限"};
    String[] s6 = {"不限"};
    String[] s7 = {"不限"};
    String[] s8 = {"不限"};
    String[] s9 = {"不限", "南坪", "南岸"};
    String[] s10 = {"不限"};
    String[] s11 = {"不限", "沙坪坝"};
    String[] s12 = {"不限", "渝中"};
    String[] s13 = {"不限", "江"};
    String[] s14 = {"不限"};
    String[] s15 = {"不限"};
    String[] s16 = {"不限"};
    String[] s17 = {"不限"};
    String[] s18 = {"不限"};
    String[][] ss = {s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18};
    for (int i = 0; i < strings.length; i++) {
        map.put(strings[i], Arrays.asList(ss[i]));
    }
    return map;
}`
```

获取 mainWheelView.getSelectionItem() subWheelView.getSelectedItem() childWheelView.getSelectedItem()，得到：重庆 null null

**Comment by venshine** [comment]
`mainWheelView.setOnWheelItemSelectedListener(new WheelView.OnWheelItemSelectedListener() {
            @Override
            public void onItemSelected(int position, Object o) {
                WheelUtils.log("main -- main:" + mainWheelView.getSelectionItem() + ", sub:" + subWheelView.getSelectionItem() + ", " +
                        "child:" + childWheelView.getSelectionItem());
            }
        });
        subWheelView.setOnWheelItemSelectedListener(new WheelView.OnWheelItemSelectedListener() {
            @Override
            public void onItemSelected(int position, Object o) {
                WheelUtils.log("sub -- main:" + mainWheelView.getSelectionItem() + ", sub:" + subWheelView.getSelectionItem() + ", " +
                        "child:" + childWheelView.getSelectionItem());
            }
        });
        childWheelView.setOnWheelItemSelectedListener(new WheelView.OnWheelItemSelectedListener() {
            @Override
            public void onItemSelected(int position, Object o) {
                WheelUtils.log("child -- main:" + mainWheelView.getSelectionItem() + ", sub:" + subWheelView.getSelectionItem() + ", " +
                        "child:" + childWheelView.getSelectionItem());
            }
        });`

> > `04-21 11:13:38.023 7585-7585/com.wx.wheelview D/WheelView: main -- main:大理, sub:不限, child:不限
> > 04-21 11:13:38.333 7585-7585/com.wx.wheelview D/WheelView: sub -- main:大理, sub:不限, child:不限
> > 04-21 11:13:38.645 7585-7585/com.wx.wheelview D/WheelView: child -- main:重庆, sub:不限, child:不限`

把你打印的逻辑代码发上来看一下，我这里没有问题。

**Comment by rewufu** [comment]
`Button button = (Button) findViewById(R.id.button);
        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Log.i("aaa", (String) mainWheelView.getSelectionItem() + (String) subWheelView.getSelectedItem() + (String) childWheelView.getSelectedItem());
                Log.i("aaa", ""+mainWheelView.getSelection() + subWheelView.getSelection() + childWheelView.getSelection());
            }
        });`
在外面有一个button，点击后打印log

**Comment by venshine** [comment]
你使用错了，应该是`getSelectionItem()`而不是`getSelectedItem()`。

**Comment by rewufu** [comment]
Sorry, 错了

**Comment by venshine** [comment]
有其他问题也欢迎随时反馈，谢谢！
