### ISSUE TITLE
Adapter只支持String类型

### ISSUE THREAD

**Issue by xiaoGuy** [venshine/WheelView#6]
虽然setWheelData的参数是List<T>，但是传入List<Integer>时就会报ClassCastException，因为把Integer强制转成了String

**Comment by xiaoGuy** [comment]
哦，原来我使用的是ArrayWheelAdapter，ArrayWheelAdapter extends BaseWheelAdapter<String>。
我觉得这里不应该指定为String，应该把item.setText()中的代码改成mList.get(position).toString()

**Comment by venshine** [comment]
已经修改支持泛型类型，请用最新代码尝试，多谢提醒。
